// stubs/Dropdown.jsx
import { useState, useEffect, useRef } from "react";
import { clsx } from "clsx";

export default function Dropdown({
    align = "right",
    width = "48",
    contentClasses = "py-1 bg-white",
    children,
}) {
    const [open, setOpen] = useState(false);
    const dropdownRef = useRef(null);

    useEffect(() => {
        const closeOnEscape = (e) => {
            if (open && e.key === "Escape") {
                setOpen(false);
            }
        };

        document.addEventListener("keydown", closeOnEscape);
        return () => document.removeEventListener("keydown", closeOnEscape);
    }, [open]);

    const widthClass = {
        48: "w-48",
    }[width.toString()];

    const alignmentClasses =
        {
            left: "origin-top-left left-0",
            right: "origin-top-right right-0",
        }[align] || "origin-top";

    return (
        <div className="relative" ref={dropdownRef}>
            <div onClick={() => setOpen(!open)}>{children.trigger}</div>

            {/* Full Screen Dropdown Overlay */}
            {open && (
                <div
                    className="fixed inset-0 z-40"
                    onClick={() => setOpen(false)}
                />
            )}

            {/* Dropdown Content */}
            <div
                className={clsx(
                    "absolute z-50 mt-2 rounded-md shadow-lg transition-all duration-200",
                    widthClass,
                    alignmentClasses,
                    open
                        ? "transform opacity-100 scale-100"
                        : "transform opacity-0 scale-95 pointer-events-none",
                )}
                onClick={() => setOpen(false)}
            >
                <div
                    className={clsx(
                        "rounded-md ring-1 ring-black ring-opacity-5",
                        contentClasses,
                    )}
                >
                    {children.content}
                </div>
            </div>
        </div>
    );
}

// Compound components
Dropdown.Trigger = function DropdownTrigger({ children }) {
    return children;
};

Dropdown.Content = function DropdownContent({ children }) {
    return children;
};

// stubs/Dropdown.vue
<template>
    <div class="relative">
        <div @click="open = !open">
            <slot name="trigger" />
        </div>

        <!-- Full Screen Dropdown Overlay -->
        <div v-show="open" class="fixed inset-0 z-40" @click="open = false" />

        <Transition
            enter-active-class="transition ease-out duration-200"
            enter-from-class="transform opacity-0 scale-95"
            enter-to-class="transform opacity-100 scale-100"
            leave-active-class="transition ease-in duration-75"
            leave-from-class="transform opacity-100 scale-100"
            leave-to-class="transform opacity-0 scale-95"
        >
            <div
                v-show="open"
                class="absolute z-50 mt-2 rounded-md shadow-lg"
                :class="[widthClass, alignmentClasses]"
                style="display: none"
                @click="open = false"
            >
                <div
                    class="rounded-md ring-1 ring-black ring-opacity-5 py-1 bg-white"
                >
                    <slot name="content" />
                </div>
            </div>
        </Transition>
    </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from "vue";

const props = defineProps({
    align: {
        type: String,
        default: "right",
    },
    width: {
        type: String,
        default: "48",
    },
    contentClasses: {
        type: String,
        default: "py-1 bg-white",
    },
});

const open = ref(false);

const closeOnEscape = (e) => {
    if (open.value && e.key === "Escape") {
        open.value = false;
    }
};

onMounted(() => document.addEventListener("keydown", closeOnEscape));
onUnmounted(() => document.removeEventListener("keydown", closeOnEscape));

const widthClass = computed(() => {
    return {
        48: "w-48",
    }[props.width.toString()];
});

const alignmentClasses = computed(() => {
    if (props.align === "left") {
        return "origin-top-left left-0";
    } else if (props.align === "right") {
        return "origin-top-right right-0";
    } else {
        return "origin-top";
    }
});
</script>
